### ISSUE TITLE
TypeError: console.debug is not a function

### ISSUE THREAD

**Issue by nahuelsanchez** [DivanteLtd/vue-storefront-api#22]
Hello everybody,

I'm not entirely sure if I'm doing something wrong and that's why I'm getting the error... or there's an actual error in the code, hehe.

When running `npm run dev` in order to have the API running, I get the following error in the Terminal:

```
[Function: HmacProcessor]
/home/ec2-user/vue-storefront-api/src/processor/default.js:24
            console.debug('Entering HmacProcessor::process');
                    ^

TypeError: console.debug is not a function
    at HmacProcessor.process (/home/ec2-user/vue-storefront-api/src/processor/default.js:12:17)
    at Request._callback (/home/ec2-user/vue-storefront-api/src/api/catalog.js:54:23)
    at Request.self.callback (/home/ec2-user/vue-storefront-api/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ec2-user/vue-storefront-api/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ec2-user/vue-storefront-api/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
[nodemon] app crashed - waiting for file changes before starting...
```

The problematic line in the code seems to be the `console.debug()` method as my understanding is that there is no `debug()` method for `console` in NodeJs

https://github.com/DivanteLtd/vue-storefront-api/blob/49c7bb17648baf8ef691d4957f53d5837bd99ff7/src/processor/default.js#L12

Is it correct to say that this line needs to be changed to `console.log()`?

**Comment by Aekal** [comment]
I think it's the same problem as mentioned here: DivanteLtd/vue-storefront#326
Try to update Node to v.8+

**Comment by nahuelsanchez** [comment]
Hi @Aekal,

Yep, updated to 8.9.4 and everything works fine. I'm closing the issue as it doesn't apply anymore.

Thanks!
