### ISSUE TITLE
 error : Error: Missing migration file: 1506760343216-example-products.js

### ISSUE THREAD

**Issue by roboto-cloud** [DivanteLtd/vue-storefront-api#23]
Hi, someone know how fix it?

```
5 info lifecycle vue-storefront-api@0.1.0~premigrate: vue-storefront-api@0.1.0
6 info lifecycle vue-storefront-api@0.1.0~migrate: vue-storefront-api@0.1.0
7 verbose lifecycle vue-storefront-api@0.1.0~migrate: unsafe-perm in lifecycle true
8 verbose lifecycle vue-storefront-api@0.1.0~migrate: PATH: /home/rbt/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/-/u/io/src/storefront/vue-storefront-api/node_modules/.bin:/home/rbt/.nvm/versions/node/v8.9.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle vue-storefront-api@0.1.0~migrate: CWD: /mnt/-/u/io/src/storefront/vue-storefront-api
10 silly lifecycle vue-storefront-api@0.1.0~migrate: Args: [ '-c', 'node node_modules/migrate/bin/migrate' ]
11 silly lifecycle vue-storefront-api@0.1.0~migrate: Returned: code: 1  signal: null
12 info lifecycle vue-storefront-api@0.1.0~migrate: Failed to exec migrate script
```

**Comment by pkarw** [comment]
Do you have any more specific logs about exac nodejs error? Hard to say from information provided. Please also advise us on the node version you use

**Comment by roboto-cloud** [comment]
hi @pkarw :)

```
yarn run migrate
yarn run v1.3.2
$ node node_modules/migrate/bin/migrate
Elasticsearch INFO: 2018-02-07T19:53:42Z
  Adding connection to http://localhost:9200/

  error : Error: Missing migration file: 1506760343216-example-products.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by pkarw** [comment]
It seems like you'd ran migrate before we changed the structure a little bit
Please try: rm .migrate; npm run migrate

**Comment by roboto-cloud** [comment]
ok @pkarw it work but buit if I run:

**→→→ yarn run dev                                                                 ✔  2723  00:10:17** 

```
yarn run v1.3.2
$ npm run fixconfigs && nodemon -w src --exec "babel-node src --presets es2015,stage-0"

> vue-storefront-api@0.1.0 fixconfigs /mnt/source-code/storefront/vue-storefront-api
> node fixconfigs.js

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /mnt/source-code/storefront/vue-storefront-api/src/**/*
[nodemon] starting `babel-node src --presets es2015,stage-0`
[nodemon] Internal watch failed: watch /mnt/source-code/storefront/vue-storefront-api/src ENOSPC
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```


**→→→ npm run dev                                                                  1 ↵  2724  00:11:18** 

```
> vue-storefront-api@0.1.0 dev /mnt/source-code/storefront/vue-storefront-api
> npm run fixconfigs && nodemon -w src --exec "babel-node src --presets es2015,stage-0"


> vue-storefront-api@0.1.0 fixconfigs /mnt/source-code/storefront/vue-storefront-api
> node fixconfigs.js                                                                                                                                                      


[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /mnt/source-code/storefront/vue-storefront-api/src/**/*
[nodemon] starting `babel-node src --presets es2015,stage-0`
[nodemon] Internal watch failed: watch /mnt/source-code/storefront/vue-storefront-api/src ENOSPC
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront-api@0.1.0 dev: `npm run fixconfigs && nodemon -w src --exec "babel-node src --presets es2015,stage-0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-storefront-api@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-02-07T23_11_50_888Z-debug.log
```

**→→→ cat /home/user/.npm/_logs/2018-02-07T23_11_50_888Z-debug.log                1 ↵  2725  00:11:51** 

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-storefront-api@0.1.0~predev: vue-storefront-api@0.1.0
6 info lifecycle vue-storefront-api@0.1.0~dev: vue-storefront-api@0.1.0
7 verbose lifecycle vue-storefront-api@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-storefront-api@0.1.0~dev: PATH: /home/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/source-code/storefront/vue-storefront-api/node_modules/.bin:/home/user/.nvm/versions/node/v8.9.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle vue-storefront-api@0.1.0~dev: CWD: /mnt/source-code/storefront/vue-storefront-api
10 silly lifecycle vue-storefront-api@0.1.0~dev: Args: [ '-c',
10 silly lifecycle   'npm run fixconfigs && nodemon -w src --exec "babel-node src --presets es2015,stage-0"' ]
11 silly lifecycle vue-storefront-api@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle vue-storefront-api@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: vue-storefront-api@0.1.0 dev: `npm run fixconfigs && nodemon -w src --exec "babel-node src --presets es2015,stage-0"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vue-storefront-api@0.1.0
15 verbose cwd /mnt/source-code/storefront/vue-storefront-api
16 verbose Linux 4.15.1-2-ARCH
17 verbose argv "/home/user/.nvm/versions/node/v8.9.4/bin/node" "/home/user/.nvm/versions/node/v8.9.4/bin/npm" "run" "dev"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-storefront-api@0.1.0 dev: `npm run fixconfigs && nodemon -w src --exec "babel-node src --presets es2015,stage-0"`
22 error Exit status 1
23 error Failed at the vue-storefront-api@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by pkarw** [comment]
Very strange; I don't have idea why is that? It's a problem related only to running with `yarn` instead of raw `npm`?

**Comment by roboto-cloud** [comment]
@pkarw, the problem is using both..
the last output is the npm log
cat /home/user/.npm/_logs/2018-02-07T23_11_50_888Z-debug.log

**Comment by pkarw** [comment]
Seems like a problem with nodemon command; what happens when you run npm run build and then npm start?

**Comment by pkarw** [comment]
OK, we haven't tested it with yarn; if it's good with npm could you then close the issue please? 

Thanks for your time, very informative tickets
