### ISSUE TITLE
Docker app node wont' start because of missing `nodemon.js`

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront-api#278]
The `app` node won't start via docker with the following error because of missing `nodemon.js` file.
```bash
$ nodemon
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node dist`
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/var/www/dist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[nodemon] app crashed - waiting for file changes before starting...
```

This is related to #272.

**Comment by lukeromanowicz** [comment]
Merged to develop. Will be introduced in 1.10 release. Thanks for your contribution!
