### ISSUE TITLE
Startup Failure graphql_1.getDescription

### ISSUE THREAD

**Issue by lrcry** [DivanteLtd/vue-storefront-api#312]
We rebuilt and redeployed VSF API yesterday and after the new build, an error occurred:

```
/var/www/node_modules/graphql-toolkit/dist/commonjs/epoxy/typedefs-mergers/comments.js:36
    const comment = graphql_1.getDescription(node, { commentDescriptions: true });
                              ^

TypeError: graphql_1.getDescription is not a function
    at pushComment (/var/www/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/comments.ts:41:19)
    at Object.collectComment (/var/www/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/comments.ts:13:3)
    at nodes.reduce (/var/www/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-nodes.ts:36:9)
    at Array.reduce (<anonymous>)
    at Object.mergeGraphQLNodes (/var/www/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-nodes.ts:29:16)
    at mergeGraphQLTypes (/var/www/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-typedefs.ts:228:40)
    at Object.mergeTypeDefs (/var/www/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-typedefs.ts:93:18)
    at mergeTypes (/var/www/node_modules/merge-graphql-schemas/src/merge_types.ts:9:10)
    at Object.<anonymous> (/var/www/src/graphql/schema.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

We found another team faced with the exactly same issue. Original source [here](Dependency Issue - TypeError: graphql_1.getDescription is not a function).

Finally we updated `graphql` dependency to version `v0.13.1` to get it back up and running. Seems no problem after the update.

Can we propose to upgrade this in the official repository here as well?

Thanks and regards
Hans

**Comment by lukeromanowicz** [comment]
Hi there, yes please :-)

**Comment by lrcry** [comment]
Thanks. We will raise a PR for this soon.

Cheers
Hans

**Comment by lrcry** [comment]
Raised. Please kindly check and merge.

Thanks
Hans
