### ISSUE TITLE
SyntaxError: Invalid regular expression: /[\p{L}\d_]+/: Invalid escape

### ISSUE THREAD

**Issue by haelbichalex** [DivanteLtd/vue-storefront-api#338]
On node v8.16.1 I get the following error in the o2m app:
```
1|o2m      | 2019-09-02 16:21:24: SyntaxError: Invalid regular expression: /[\p{L}\d_]+/: Invalid escape
1|o2m      | 2019-09-02 16:21:24:     at Object.<anonymous> (src/models/order.schema.js:1:19)
1|o2m      | 2019-09-02 16:21:24:     at Module._compile (module.js:653:30)
1|o2m      | 2019-09-02 16:21:24:     at Object.Module._extensions..js (module.js:664:10)
1|o2m      | 2019-09-02 16:21:24:     at Module.load (module.js:566:32)
1|o2m      | 2019-09-02 16:21:24:     at tryModuleLoad (module.js:506:12)
1|o2m      | 2019-09-02 16:21:24:     at Function.Module._load (module.js:498:3)
1|o2m      | 2019-09-02 16:21:24:     at Function._load (/usr/lib/node_modules/pm2/node_modules/@pm2/io/src/metrics/httpMetrics.ts:190:35)
1|o2m      | 2019-09-02 16:21:24:     at Module.require (module.js:597:17)
1|o2m      | 2019-09-02 16:21:24:     at require (internal/module.js:11:18)
1|o2m      | 2019-09-02 16:21:24:     at Object.<anonymous> (src/platform/magento2/o2m.js:19:21)
```

Using node v10 fixes the problem, [README.md](https://github.com/DivanteLtd/vue-storefront-api/blob/master/README.md#requirements) says node v8 should work though: `Node.js 8.x or higher`.

**Comment by pkarw** [comment]
OK, thanks for checking this out; requiring node 10 is pretty much safe; it's stable in the end; can you please modify the docs  + package.json/

**Comment by haelbichalex** [comment]
@pkarw I didn't find a reference to the node version in `package.json`, so I updated only the readme. Let me know if there's anything todo in some other files.

**Comment by steffen-wirth** [comment]
Hi,
we are restricted for now on 32bit server and node 10 is not available for 32bit. Seems like in the regexp /[\p{L}\d_]+/u the u is not allowed like posted [here](https://github.com/slevithan/xregexp/issues/197)
If i remove the u i get no errors anymore but what to expect then ?

**Comment by rebinti** [comment]
I got the same error when I am using Node 10.15.1 or 10.16.3
I just removed the 'u' from the exp
/[\p{L}\d_]+/u  ->   /[\p{L}\d_]+/
Now I get no errors anymore
