### ISSUE TITLE
Error during making orders (SyntaxError: Invalid regular expression)

### ISSUE THREAD

**Issue by andrzejewsky** [DivanteLtd/vue-storefront-api#351]
In some cases (probably depends on node version) the making orders doesn't work. The API raises error as this one below:

```
 SyntaxError: Invalid regular expression: /[\p{L}\d_]+/: Invalid escape
    at Object.<anonymous> (/var/www/src/models/order.schema.js:1:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at create (/var/www/src/api/order.js:31:23)
    at Layer.handle [as handle_request] (/var/www/node_modules/express/lib/router/layer.js:95:5) 
```

Would be nice to solve that error / regex to be compatible with even older versions of node as we cannot upgrade node everywhere immediately (other hosting providers)

**Comment by lukeromanowicz** [comment]
It's because Node 8 is not supported by the API anymore and there is no good workaround for that. Older versions don't support unicode regex and babel is not transpiling that regex properly. You could put there a ~2kb long regex instead that will do the same job but EOL of Node 8 is next month anyway. I'm not sure if uglifying the source code is worth it.

**Comment by ArturDivante** [comment]
@andrzejewsky @lukeromanowicz @patzick
FYI: 
Exactly the same problem still occurs now on next and test environments

**Comment by pkarw** [comment]
@andrzejewsky has this one been already fixed?
