### ISSUE TITLE
Error "Cannot use import statement outside a module" 

### ISSUE THREAD

**Issue by o2bj** [DivanteLtd/vue-storefront-api#437]
env:
- windows 10
- node v12.16.2
- yarn 1.22.4

```
C:\Users\bajg\Documents\VisualStudioCode\vue-storefront-api>yarn o2m
yarn run v1.22.4
$ node src/worker/order_to_magento2.js start
info: Winston logging library initialized.
error: uncaughtException: Cannot use import statement outside a module date=Thu Apr 16 2020 14:26:32 GMT+0200 (GMT+02:00), pid=24200, uid=null, gid=null, cwd=C:\Users\bajg\Documents\VisualStudioCode\vue-storefront-api, execPath=C:\Program Files\nodejs\node.exe, version=v12.16.2, argv=[C:\Program Files\nodejs\node.exe, C:\Users\bajg\Documents\VisualStudioCode\vue-storefront-api\src\worker\order_to_magento2.js, start], rss=55709696, heapTotal=34082816, heapUsed=19816280, external=1547039, loadavg=[0, 0, 0], uptime=26838, trace=[column=16, file=internal/modules/cjs/loader.js, function=wrapSafe, line=1070, method=null, native=false, column=27, file=internal/modules/cjs/loader.js, function=Module._compile, line=1120, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Module._extensions..js, line=1176, method=.js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=1000, method=load, native=false, column=14, file=internal/modules/cjs/loader.js, function=Module._load, line=899, method=_load, native=false, column=19, file=internal/modules/cjs/loader.js, function=Module.require, line=1042, method=require, native=false, column=18, file=internal/modules/cjs/helpers.js, function=require, line=77, method=null, native=false, column=15, file=C:\Users\bajg\Documents\VisualStudioCode\vue-storefront-api\src\platform\magento2\o2m.js, function=null, line=5, method=null, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=1156, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Module._extensions..js, line=1176, method=.js, native=false], stack=[C:\Users\bajg\Documents\VisualStudioCode\vue-storefront-api\src\lib\redis.js:1, import Redis from 'redis', ^^^^^^, , SyntaxError: Cannot use import statement outside a module,     at wrapSafe (internal/modules/cjs/loader.js:1070:16),     at Module._compile (internal/modules/cjs/loader.js:1120:27),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10),     at Module.load (internal/modules/cjs/loader.js:1000:32),     at Function.Module._load (internal/modules/cjs/loader.js:899:14),     at Module.require (internal/modules/cjs/loader.js:1042:19),     at require (internal/modules/cjs/helpers.js:77:18),     at Object.<anonymous> (C:\Users\bajg\Documents\VisualStudioCode\vue-storefront-api\src\platform\magento2\o2m.js:5:15),     at Module._compile (internal/modules/cjs/loader.js:1156:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)]
```

**Comment by o2bj** [comment]
i try also this runing "vuestorefront-api" as docker instance and and then i have different error: 

```
C:\Users\bajg\Documents\VisualStudioCode\vue-storefront-api>docker exec -it 5c79b4b89dcb yarn o2m-anon
yarn run v1.22.4
$ node src/worker/order_to_magento2.js testAnon
info: Winston logging library initialized.
error: uncaughtException: Unexpected identifier date=Fri Apr 17 2020 08:50:57 GMT+0000 (Coordinated Universal Time), pid=325, uid=0, gid=0, cwd=/var/www, execPath=/usr/local/bin/node, version=v10.20.1, argv=[/usr/local/bin/node, /var/www/src/worker/order_to_magento2.js, testAnon], rss=60088320, heapTotal=38576128, heapUsed=22470632, external=498227, loadavg=[0, 0.0087890625, 0], uptime=4650, trace=[column=23, file=internal/modules/cjs/loader.js, function=Module._compile, line=723, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Module._extensions..js, line=789, method=.js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=653, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=593, method=null, native=false, column=3, file=internal/modules/cjs/loader.js, function=Module._load, line=585, method=_load, native=false, column=17, file=internal/modules/cjs/loader.js, function=Module.require, line=692, method=require, native=false, column=18, file=internal/modules/cjs/helpers.js, function=require, line=25, method=null, native=false, column=15, file=/var/www/src/platform/magento2/o2m.js, function=null, line=5, method=null, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=778, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Module._extensions..js, line=789, method=.js, native=false], stack=[/var/www/src/lib/redis.js:1, import Redis from 'redis',        ^^^^^, , SyntaxError: Unexpected identifier,     at Module._compile (internal/modules/cjs/loader.js:723:23),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),     at Module.load (internal/modules/cjs/loader.js:653:32),     at tryModuleLoad (internal/modules/cjs/loader.js:593:12),     at Function.Module._load (internal/modules/cjs/loader.js:585:3),     at Module.require (internal/modules/cjs/loader.js:692:17),     at require (internal/modules/cjs/helpers.js:25:18),     at Object.<anonymous> (/var/www/src/platform/magento2/o2m.js:5:15),     at Module._compile (internal/modules/cjs/loader.js:778:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)]
```

**Comment by gibkigonzo** [comment]
problem is that in `src/platform/magento2/o2m.js` we want to require file that is in different module system. As we have ts here we can just change `"o2m": "node src/worker/order_to_magento2.js start",` to `"o2m": "ts-node src/worker/order_to_magento2.js start",` I will make pr for that

**Comment by o2bj** [comment]
@gibkigonzo  thanks that help. 

I have question for you, person with no node js knowledge will handle vue storefront integration? 

I tested manually (yarn o2m-anon" because in storevuefront 
`Request URL: http://localhost:8080/api/order`
gives me 500 with no error Description:  
`{"code":500,"result":{}}`

In "vue-storefront-api" catalog i do not see any "log" folder which could help find issue, there should be any logs in case like this?

Now after "yarn o2m-anon" i see that there was no available payment method.

**Comment by gibkigonzo** [comment]
Yes you can, it's always good to know how node works, but vsf-api is more like proxy between your backend (for example magento) + es and vsf. Right now we are working more on https://github.com/DivanteLtd/storefront-api which is focused on graphql and has more modular architecture (but still in development). There will be probably better logging, but any pr here is welcomed :)

**Comment by gibkigonzo** [comment]
closed by https://github.com/DivanteLtd/vue-storefront-api/pull/439
