### ISSUE TITLE
Docker is missing python (and make) in dockerfile build

### ISSUE THREAD

**Issue by ProxiBlue** [DivanteLtd/vue-storefront-api#448]
Building the docker file, as provided in repo, yarn install / build fails.

```
....

[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > graphql-tools@1.2.3" has incorrect peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0".
[5/5] Building fresh packages...
error /buddy/vue-storefront-api/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /buddy/vue-storefront-api/node_modules/sharp
Output:
info sharp Using cached /root/.npm/_libvips/libvips-8.8.1-linuxmusl-x64.tar.gz
Segmentation fault (core dumped)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.20.1 | linux | x64
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Linux 4.15.0-1032-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /buddy/vue-storefront-api/node_modules/sharp
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
FAILEDAction failed: see logs above for details
```

If I add python and make to the docker file, issue is resolved.

**Comment by ProxiBlue** [comment]
Correction, adding the python and make to the Docker build gets me further, but still breaks.
Full docker build log here:

I now get: make: g++: Command not found

```
docker build --cpu-period=100000 --cpu-quota=200000 -m 2048m --force-rm=true -t 245243_590456:latest --pull -f "docker/vue-storefront-api/Dockerfile" .
Sending build context to Docker daemon  336.8MB
Step 1/9 : FROM node:10-alpine
10-alpine: Pulling from library/node
Digest: sha256:b2db1b026f1b01a6a91f39d8204b89c5c13d2b40a017dd4d9253ab066c9cf2cb
Status: Image is up to date for node:10-alpine
 ---> a07f309c9753
Step 2/9 : ENV VS_ENV prod
 ---> Running in 0744b1005bd6
Removing intermediate container 0744b1005bd6
 ---> c98a552ed23d
Step 3/9 : WORKDIR /var/www
 ---> Running in d499b2194615
Removing intermediate container d499b2194615
 ---> 59612f657102
Step 4/9 : RUN apk add --no-cache curl git
 ---> Running in 1ff4d7873967
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20191127-r1)
(2/7) Installing nghttp2-libs (1.40.0-r0)
(3/7) Installing libcurl (7.67.0-r0)
(4/7) Installing curl (7.67.0-r0)
(5/7) Installing expat (2.2.9-r1)
(6/7) Installing pcre2 (10.34-r1)
(7/7) Installing git (2.24.3-r0)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
OK: 24 MiB in 23 packages
Removing intermediate container 1ff4d7873967
 ---> 7b6d11521142
Step 5/9 : COPY package.json ./
 ---> 422f3bc2a1f5
Step 6/9 : COPY yarn.lock ./
 ---> d7bec48e5300
Step 7/9 : RUN apk add --no-cache --virtual .build-deps ca-certificates wget python make &&     yarn install --no-cache &&     apk del .build-deps
 ---> Running in 5ef8b9bf6312
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/11) Installing wget (1.20.3-r0)
(2/11) Installing libbz2 (1.0.8-r1)
(3/11) Installing libffi (3.2.1-r6)
(4/11) Installing gdbm (1.13-r1)
(5/11) Installing ncurses-terminfo-base (6.1_p20200118-r4)
(6/11) Installing ncurses-libs (6.1_p20200118-r4)
(7/11) Installing readline (8.0.1-r0)
(8/11) Installing sqlite-libs (3.30.1-r2)
(9/11) Installing python2 (2.7.18-r0)
(10/11) Installing make (4.2.1-r2)
(11/11) Installing .build-deps (20200518.070442)
Executing busybox-1.31.1-r9.trigger
OK: 65 MiB in 34 packages
yarn install v1.22.4
info Merge conflict detected in yarn.lock and successfully merged.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > graphql-tools@1.2.3" has incorrect peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0".
[5/5] Building fresh packages...
error /var/www/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /var/www/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linuxmusl-x64.tar.gz
Segmentation fault (core dumped)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.20.1 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python"
gyp http GET https://unofficial-builds.nodejs.org/download/release/v10.20.1/node-v10.20.1-headers.tar.gz
gyp http 200 https://unofficial-builds.nodejs.org/download/release/v10.20.1/node-v10.20.1-headers.tar.gz
gyp http GET https://unofficial-builds.nodejs.org/download/release/v10.20.1/SHASUMS256.txt
gyp http 200 https://unofficial-builds.nodejs.org/download/release/v10.20.1/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/10.20.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/10.20.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/10.20.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/var/www/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
make: g++: Command not found
make: *** [sharp.target.mk:129: Release/obj.target/sharp/src/common.o] Error 127
make: Leaving directory '/var/www/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-1032-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/node_modules/sharp
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Removing intermediate container 5ef8b9bf6312
The command '/bin/sh -c apk add --no-cache --virtual .build-deps ca-certificates wget python make &&     yarn install --no-cache &&     apk del .build-deps' returned a non-zero code: 1
docker image prune -f
Deleted Images:
deleted: sha256:d7bec48e53000589e7adaddbb273465fcc40ff315bca7ec848f278bf5e5befce
deleted: sha256:475ef2d891333432293071979b0a4ce79cdd924e35f7d07fea3464195e1322b0
deleted: sha256:422f3bc2a1f5fd4fcfe1da0061de974f9cecbd85772bb3a6feac8a4eecfd7004
deleted: sha256:d0f41f2cc0df2493076eb652e6f7a4133564f382f41a11567723c708206067c7
deleted: sha256:7b6d115211427c3d53b777ed6f03846d7ec2458eda4c1e9b8688c0c56dcae3a7
deleted: sha256:695ca752368183e6545da55b54fb9d6ab6758c0d94151b58f4aef0b8c5334010
deleted: sha256:59612f6571027a57862466d987b39a21a945c0c65c71f7b9224f4d89ab966fc0
deleted: sha256:3bd93b2bfc03df2b7cd9501e337a0112b611dff777531aa36544f2c965c34e18
deleted: sha256:c98a552ed23dd4e2feef396c45b6413e4a537aab688aab17b32af3c2c4bdcbe7
Total reclaimed space: 16.79MB
Action failed: see logs above for details
```

**Comment by ProxiBlue** [comment]
Adding in g++ to dockerfile resolves issue further, and build now completes.

```
docker build --cpu-period=100000 --cpu-quota=200000 -m 2048m --force-rm=true -t 245243_590456:latest --pull -f "docker/vue-storefront-api/Dockerfile" .
Sending build context to Docker daemon  345.3MB
Step 1/9 : FROM node:10-alpine
10-alpine: Pulling from library/node
Digest: sha256:b2db1b026f1b01a6a91f39d8204b89c5c13d2b40a017dd4d9253ab066c9cf2cb
Status: Image is up to date for node:10-alpine
 ---> a07f309c9753
Step 2/9 : ENV VS_ENV prod
 ---> Running in c423ac2e5b3c
Removing intermediate container c423ac2e5b3c
 ---> 4601849d89f2
Step 3/9 : WORKDIR /var/www
 ---> Running in 1584592d2e52
Removing intermediate container 1584592d2e52
 ---> 9090b7975ce0
Step 4/9 : RUN apk add --no-cache curl git
 ---> Running in e372aaaeb375
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20191127-r1)
(2/7) Installing nghttp2-libs (1.40.0-r0)
(3/7) Installing libcurl (7.67.0-r0)
(4/7) Installing curl (7.67.0-r0)
(5/7) Installing expat (2.2.9-r1)
(6/7) Installing pcre2 (10.34-r1)
(7/7) Installing git (2.24.3-r0)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
OK: 24 MiB in 23 packages
Removing intermediate container e372aaaeb375
 ---> 55c5a6056714
Step 5/9 : COPY package.json ./
 ---> cdd5712c5618
Step 6/9 : COPY yarn.lock ./
 ---> caef983e1dfb
Step 7/9 : RUN apk add --no-cache --virtual .build-deps ca-certificates wget python make g++ &&     yarn install --no-cache &&     apk del .build-deps
 ---> Running in 670d0d20455b
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/22) Installing wget (1.20.3-r0)
(2/22) Installing libbz2 (1.0.8-r1)
(3/22) Installing libffi (3.2.1-r6)
(4/22) Installing gdbm (1.13-r1)
(5/22) Installing ncurses-terminfo-base (6.1_p20200118-r4)
(6/22) Installing ncurses-libs (6.1_p20200118-r4)
(7/22) Installing readline (8.0.1-r0)
(8/22) Installing sqlite-libs (3.30.1-r2)
(9/22) Installing python2 (2.7.18-r0)
(10/22) Installing make (4.2.1-r2)
(11/22) Installing binutils (2.33.1-r0)
(12/22) Installing gmp (6.1.2-r1)
(13/22) Installing isl (0.18-r0)
(14/22) Installing libgomp (9.2.0-r4)
(15/22) Installing libatomic (9.2.0-r4)
(16/22) Installing mpfr4 (4.0.2-r1)
(17/22) Installing mpc1 (1.1.0-r1)
(18/22) Installing gcc (9.2.0-r4)
(19/22) Installing musl-dev (1.1.24-r2)
(20/22) Installing libc-dev (0.7.2-r0)
(21/22) Installing g++ (9.2.0-r4)
(22/22) Installing .build-deps (20200518.071150)
Executing busybox-1.31.1-r9.trigger
OK: 228 MiB in 45 packages
yarn install v1.22.4
info Merge conflict detected in yarn.lock and successfully merged.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > graphql-tools@1.2.3" has incorrect peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 29.23s.
WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
(1/22) Purging .build-deps (20200518.071150)
(2/22) Purging wget (1.20.3-r0)
(3/22) Purging make (4.2.1-r2)
(4/22) Purging g++ (9.2.0-r4)
(5/22) Purging gcc (9.2.0-r4)
(6/22) Purging binutils (2.33.1-r0)
(7/22) Purging libatomic (9.2.0-r4)
(8/22) Purging libgomp (9.2.0-r4)
(9/22) Purging libc-dev (0.7.2-r0)
(10/22) Purging musl-dev (1.1.24-r2)
(11/22) Purging python2 (2.7.18-r0)
(12/22) Purging libbz2 (1.0.8-r1)
(13/22) Purging libffi (3.2.1-r6)
(14/22) Purging gdbm (1.13-r1)
(15/22) Purging readline (8.0.1-r0)
(16/22) Purging ncurses-libs (6.1_p20200118-r4)
(17/22) Purging ncurses-terminfo-base (6.1_p20200118-r4)
(18/22) Purging sqlite-libs (3.30.1-r2)
(19/22) Purging isl (0.18-r0)
(20/22) Purging mpc1 (1.1.0-r1)
(21/22) Purging mpfr4 (4.0.2-r1)
(22/22) Purging gmp (6.1.2-r1)
Executing busybox-1.31.1-r9.trigger
OK: 24 MiB in 23 packages
Removing intermediate container 670d0d20455b
 ---> fcf2743e20eb
Step 8/9 : COPY docker/vue-storefront-api/vue-storefront-api.sh /usr/local/bin/
 ---> 0c47a65a9e0b
Step 9/9 : CMD ["vue-storefront-api.sh"]
 ---> Running in 2ea394c67b94
Removing intermediate container 2ea394c67b94
 ---> 79a121296277
Successfully built 79a121296277
Successfully tagged 245243_590456:latest
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
245243_590456       latest              79a121296277        1 second ago        615MB
node                10-alpine           a07f309c9753        3 weeks ago         83.8MB
docker save -o /saved-images/245243_590456.tar 245243_590456:latest
docker image prune -f
Total reclaimed space: 0B
Build finished successfully!.
```

**Comment by pkarw** [comment]
thx!
